# Generated by Django 5.2.13 on 2026-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0076_normalize_all_day_visit_end_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='focal_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='focal_y',
            field=models.FloatField(default=0.5),
        ),
    ]
