# Generated by Django 5.2.13 on 2026-09-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0077_contentimage_focal_x_contentimage_focal_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
