# Generated by Django 5.2.13 on 2026-09-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0078_lodging_distance_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodging',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='visit',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
