# Generated by Django 5.2.13 on 2026-09-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0079_remove_lodging_distance_km_visit_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='linked_to_previous',
            field=models.BooleanField(default=False),
        ),
    ]
