# Generated by Django 5.2.13 on 2026-09-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
